// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhXPtKvwD10rxqttadB52MxtyyZ37yNI',
    appId: '1:1088120563863:web:6a239ce916880e907421d2',
    messagingSenderId: '1088120563863',
    projectId: 'restaurantadminpanel-ec989',
    authDomain: 'restaurantadminpanel-ec989.firebaseapp.com',
    storageBucket: 'restaurantadminpanel-ec989.appspot.com',
    measurementId: 'G-B6LSS7LBZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwRoth1pKg0fFIGEPDQdAfbehgbg3wVo',
    appId: '1:1088120563863:android:c7939c6a1c2a81697421d2',
    messagingSenderId: '1088120563863',
    projectId: 'restaurantadminpanel-ec989',
    storageBucket: 'restaurantadminpanel-ec989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMYsCHjUaqFDg2Cr3gswZwW__3BVSQjGM',
    appId: '1:1088120563863:ios:ee6343783abba0927421d2',
    messagingSenderId: '1088120563863',
    projectId: 'restaurantadminpanel-ec989',
    storageBucket: 'restaurantadminpanel-ec989.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMYsCHjUaqFDg2Cr3gswZwW__3BVSQjGM',
    appId: '1:1088120563863:ios:ee6343783abba0927421d2',
    messagingSenderId: '1088120563863',
    projectId: 'restaurantadminpanel-ec989',
    storageBucket: 'restaurantadminpanel-ec989.appspot.com',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABhXPtKvwD10rxqttadB52MxtyyZ37yNI',
    appId: '1:1088120563863:web:f5217b9e678fcde57421d2',
    messagingSenderId: '1088120563863',
    projectId: 'restaurantadminpanel-ec989',
    authDomain: 'restaurantadminpanel-ec989.firebaseapp.com',
    storageBucket: 'restaurantadminpanel-ec989.appspot.com',
    measurementId: 'G-SEQ80D604H',
  );

}