default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1088120563863:android:c7939c6a1c2a81697421d2",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "shifoashraf75@gmail.com, ashraf.sherif.eg@gmail.com",
        release_notes: "First Fastlane Firebase Distribution Release using GitHub Actions !"
      )
  end
end
