name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for pushing changes to the repository
      actions: write
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.160.0
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android