name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Required for pushing changes to the repository
      actions: write
    steps:
      - name: Checkout my repos code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Increment Flutter Version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 1)
          build=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 2)
          new_build=$((build + 1))
          sed -i "s/^version: .*/version: $version+$new_build/" pubspec.yaml

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create e.env File
        run: |
          mkdir -p assets
          echo "BASE_URL=${{ secrets.BASE_URL }}" > assets/e.env
          echo "PAYMENT_KEY=${{ secrets.PAYMENT_KEY }}" >> assets/e.env
          echo "PAYMENT_IFRAME=${{ secrets.PAYMENT_IFRAME }}" >> assets/e.env
          echo "AUTH_TOKEN_URL=${{ secrets.AUTH_TOKEN_URL }}" >> assets/e.env
          echo "TRANSACTION_INQUIRY_URL=${{ secrets.TRANSACTION_INQUIRY_URL }}" >> assets/e.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> assets/e.env
          echo "PAYMENT_METHOD=${{ secrets.PAYMENT_METHOD }}" >> assets/e.env

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
